### ISSUE TITLE
Can't change the coin [IMPROVEMENT]

### ISSUE THREAD

**Issue by Mihay28** [brinc-finance/brinc-bugbounty#18]
Can't change the coin 
![4](https://user-images.githubusercontent.com/46828978/115122175-43ccd780-9fbf-11eb-8dcb-07f918f1efe7.png)

**Comment by araskachoi** [comment]
Hello, thank you for your submission! 
This is actually expected behaviour, as our DApp is not meant to act as a DEX. We only allow the purchase of the Brinc (BRQ) token, however, you will be able to purchase the BRQ with the number of tokens we have available.
